/*
 * Constants.h
 *
 *  Created on: 16 nov. 2016
 *      Author: centelld
 */

#ifndef INCLUDE_WIRELESS_ARDUSUB_CONSTANTS_H_
#define INCLUDE_WIRELESS_ARDUSUB_CONSTANTS_H_

namespace wireless_ardusub {

#define USBL_ACOUSTIC_ADDR 1
#define GIRONA_ACOUSTIC_ADDR 2
#define EVO_BUFFER_SIZE 9000
#define MAX_NOTIFICATION_LENGTH 1024
#define MAX_CMDNAME_LENGTH 20
#define MAX_NOTIFICATION_LENGHTFIELD_LENGTH 4
#define MAX_HROVSTATE_LENGHT 40
#define BES_LENGTH 3

static const int S100_MAX_BITRATE = 1950;
}

#endif /* INCLUDE_WIRELESS_ARDUSUB_CONSTANTS_H_ */
